org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

# Minecraft Properties
minecraft_version=1.20.1

# Forge Properties
forge_version=47.4.13

# Mod Properties
mod_version=1.1.0-monifactory
maven_group=com.hepdd.ae2emicraftingforge
mod_id=ae2emicraftingforge
mod_name=AE2 EMI Crafting Integration Forge Port
mod_url=
mod_authors=liansishen
mod_license=LGPLv3.0
mod_description=
mod_issue_tracker=

# Dependencies
ae2_version=15.4.10-cosmolite.36
emi_version=1.1.22+1.20.1
mixinextras_version=0.2.0
